name: ${project.artifactId}
version: ${project.version}
api-version: 1.13
description: ${project.description}
author: mattboy9921 (mattboy9921@aim.com)
website: https://www.spigotmc.org/resources/skipnight.48334/
softdepend: [PlayerActivity]
main: net.mattlabs.skipnight.SkipNight
permissions:
  skipnight.vote.night:
    description: Allows player to vote to skip the night.
  skipnight.vote.day:
    description: Allows player to vote to skip the day.